### ISSUE TITLE
Clean up the tests

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/libff#11]
It may be good to use gtest or something like that in the tests  of libff in order to have something better than plain `asserts`.

**Comment by AntoineRondelet** [comment]
Thoughts @dtebbs?

**Comment by AntoineRondelet** [comment]
Related to: https://github.com/scipr-lab/libff/issues/46

**Comment by dtebbs** [comment]
#42 moves tests to gtest.  (Feel free to reopen if there is more to address here.)
